# Site settings
title: Tech Musings
email: steven.landers@gmail.com
description: "Various technical solutions and thoughts"
baseurl: ""
url: "http://www.stevenlanders.com"
github_username:  stevenlanders

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title.html
